version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: novabook_user
      POSTGRES_PASSWORD: novabook_pass
      POSTGRES_DB: novabook_db
    ports:
      - '5432:5432'
    volumes:
      - ./db/volume:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - db
